### ISSUE TITLE
add a function like fillna in pandas

### ISSUE THREAD

**Issue by monopolynomial** [sl-solution/InMemoryDatasets.jl#41]
would you please consider adding a `fillna` function into your package? thanks

**Comment by sl-solution** [comment]
I would be happy. But I think the name of function is important in this case. `fillna` is not very useful since `Julia` has `missing`. In `byrow` I used `fill`/`fill!` to address this but this might be confusing in general. `fillmissing` is another option, however, in `byrow` user can fill other values too. So if you have any good name for the function let me know and I add it to the package. I will be happy to change `fill`/`fill!` in `byrow` too.

**Comment by monopolynomial** [comment]
How about `ffill` and `bfill` from pandas [ffill](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ffill.html), [bfill](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.bfill.html)?

**Comment by sl-solution** [comment]
I guess `ffill` and `bfill` are adequate, if there wasn't any other idea I will add them to `IMD`.
