### ISSUE TITLE
Would you please check `Julia` Discourse time to time 

### ISSUE THREAD

**Issue by monopolynomial** [sl-solution/InMemoryDatasets.jl#96]
to answer questions and respond to misunderstandings about InMemoryDatasets?

**Comment by sl-solution** [comment]
I am a little busy at the moment due to involvement in several projects, however, I will comment on topics that mention my name. I think, there are many knowledgeable users in discourse to answer questions, especially, those who are expert in `DataFrames` should be able to answer `InMemoryDatasets`' related questions. Anyway, please feel free to mention my name in any topic that you think I should comment.
